Web/StudentsSocialMedia.Web/Controllers/CommentsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using StudentsSocialMedia.Data.Models;
using StudentsSocialMedia.Services.Data;
using StudentsSocialMedia.Web.ViewModels.Comments;
using StudentsSocialMedia.Web.ViewModels.Home;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace StudentsSocialMedia.Web.Controllers
{
    public class CommentsController : Controller
    {
        private readonly ICommentsService commentsService;
        private readonly UserManager<ApplicationUser> userManager;

        public CommentsController(ICommentsService commentsService, UserManager<ApplicationUser> userManager)
        {
            this.commentsService = commentsService;
            this.userManager = userManager;
        }

        public IActionResult AllById(string id)
        {
            AllViewModelList viewModel = new AllViewModelList
            {
                Comments = this.commentsService.GetAll<AllViewModel>(id),
            };

            return this.View(viewModel);
        }

        [Authorize]
        public IActionResult Create(string id)
        {
            return this.View();
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> Create(string id, CreateCommentInputModel input)
        {
            if (!this.ModelState.IsValid)
            {
                return this.Redirect($"/Comments/Create/{id}");
            }

            ApplicationUser user = await this.userManager.GetUserAsync(this.User);
            input.PostId = id;
            input.AuthorId = user.Id;
            await this.commentsService.CreateAsync(input);

            return this.Redirect("/");
        }
    }
}

Web/StudentsSocialMedia.Web/Controllers/ProfilesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using StudentsSocialMedia.Data.Models;
using StudentsSocialMedia.Services.Data;
using StudentsSocialMedia.Web.ViewModels.Followers;
using StudentsSocialMedia.Web.ViewModels.Images;
using StudentsSocialMedia.Web.ViewModels.Posts;
using StudentsSocialMedia.Web.ViewModels.Profiles;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace StudentsSocialMedia.Web.Controllers
{
    public class ProfilesController : Controller
    {
        private readonly IPostsService postsService;
        private readonly IImagesService imagesService;
        private readonly IFollowersService followersService;
        private readonly IUsersService usersService;
        private readonly UserManager<ApplicationUser> userManager;

        public ProfilesController(
            IPostsService postsService,
            IImagesService imagesService,
            IFollowersService followersService,
            IUsersService usersService,
            UserManager<ApplicationUser> userManager)
        {
            this.postsService = postsService;
            this.imagesService = imagesService;
            this.followersService = followersService;
            this.usersService = usersService;
            this.userManager = userManager;
        }

        [Authorize]
        public IActionResult Profile(string id)
        {
            ProfileViewModel viewModel = new ProfileViewModel
            {
                UserInfo = this.usersService.GetByUsername<UserViewModel>(id),
                Posts = this.postsService.GetAllByUsername<AllPostsViewModel>(id),
                LastPhotos = this.imagesService.GetAllByUsername<AllImagesViewModel>(id),
                Followers = this.followersService.GetAllByUsername<AllFollowersViewModel>(id),
            };

            return this.View(viewModel);
        }

        [Authorize]
        public IActionResult About(string id)
        {
            return this.View();
        }

        [Authorize]
        public IActionResult Friends(string id)
        {
            return this.View();
        }
    }
}

Web/StudentsSocialMedia.Web/Controllers/RepliesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using StudentsSocialMedia.Data.Models;
using StudentsSocialMedia.Services.Data;
using StudentsSocialMedia.Web.ViewModels.Home;
using StudentsSocialMedia.Web.ViewModels.Replies;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace StudentsSocialMedia.Web.Controllers
{
    public class RepliesController : Controller
    {
        private readonly IRepliesService repliesService;
        private readonly UserManager<ApplicationUser> userManager;

        public RepliesController(IRepliesService repliesService, UserManager<ApplicationUser> userManager)
        {
            this.repliesService = repliesService;
            this.userManager = userManager;
        }

        public IActionResult AllById(string id)
        {
            AllRepliesListViewModel viewModel = new AllRepliesListViewModel
            {
                Replies = this.repliesService.GetAll<AllRepliesViewModel>(id),
            };

            return this.View(viewModel);
        }

        [Authorize]
        public IActionResult Create(string id)
        {
            return this.View();
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> Create(string id, CreateReplyInputModel input)
        {
            if (!this.ModelState.IsValid)
            {
                return this.Redirect($"/Replies/Create/{id}");
            }

            ApplicationUser user = await this.userManager.GetUserAsync(this.User);
            input.CommentId = id;
            input.AuthorId = user.Id;
            await this.repliesService.Create(input);

            return this.Redirect("/");
        }
    }
}

Web/StudentsSocialMedia.Web/Views/Comments/AllById.cshtml
@model StudentsSocialMedia.Web.ViewModels.Comments.AllViewModelList
@{
    this.ViewData["Title"] = "All comments for this post";
}

<h1>@this.ViewData["Title"]</h1>
@if (this.Model.CommentsCount == 0)
{
    <h2>There are no comments for this post yet!</h2>
}
else
{
    @foreach (var comment in this.Model.Comments)
    {
        <ul class="comments-list">
            <li class="comment-item">
                <div class="post__author author vcard inline-items">
                    <img loading="lazy" src="@comment.AuthorImageUrl" alt="author">

                    <div class="author-date">
                        <a class="h6 post__author-name fn" asp-controller="Profiles" asp-action="Profile" asp-route-id="@comment.AuthorId">@comment.AuthorUserName</a>
                        <div class="post__date">
                            <time class="published">
                                @comment.CreatedOn
                            </time>
                        </div>
                    </div>

                    <a href="#" class="more"><svg class="olymp-three-dots-icon"><use xlink:href="#olymp-three-dots-icon"></use></svg></a>

                </div>

                <p>@comment.Content</p>

                <a asp-controller="Replies" asp-action="AllById" asp-route-id="@comment.Id" class="btn btn-primary btn-md-2">View all replies for this comment</a>

                <a href="#" class="post-add-icon inline-items">
                    <svg class="olymp-heart-icon"><use xlink:href="#olymp-heart-icon"></use></svg>
                    <span>3</span>
                </a>
                <a asp-controller="Replies" asp-action="Create" asp-route-id="@comment.Id" class="btn btn-primary btn-md-2">Reply</a>
            </li>
        </ul>
    }
}

Web/StudentsSocialMedia.Web/Views/Comments/Create.cshtml
@model StudentsSocialMedia.Web.ViewModels.Home.CreateCommentInputModel
@{ 
    this.ViewData["Title"] = "Add a comment";
}

<form method="post" class="col-md-6 offset-3-md">
    <div asp-validation-summary="All" class="text-danger"></div>

    <div class="form-group">
        <label asp-for="Content"></label>
        <textarea asp-for="Content" class="form-control" rows="10"></textarea>
        <span asp-validation-for="Content" class="text-danger"></span>
    </div>

    <input type="submit" class="btn btn-primary btn-md-2" value="Submit" />
</form>